name: kagajpatra
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.0-388.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  adaptive_sizer: ^0.0.4
  #firebase
  firebase_core: ^2.7.0

  #using the google fonts
  google_fonts: ^4.0.1

  #State Management 
  get: ^4.6.5

  # path: ^1.6.2
  # path_provider: 0.5.0+1
  # flutter_file_manager: ^0.2.0
  
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.2.9
  path_provider: ^2.0.13
  file_manager: ^1.0.1
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

 