name: kagajpatra
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.0-388.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  adaptive_sizer: ^0.0.4

  
  #firebase
  firebase_core: ^2.7.0
  firebase_auth: ^4.2.9

  #using the google fonts
  google_fonts: ^4.0.1

  #State Management 
  flutter_bloc: ^8.1.2

  #filehandling
  path_provider: ^2.0.13
  file_manager: ^1.0.1
  permission_handler: ^10.2.0
  path: ^1.8.2
  
  
  cupertino_icons: ^1.0.2
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

 